# Workflow Name
name: Hello World 2

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: run git status
      run: git status
    - name: Run one line script
      run: echo hello world
    - name : Run 2 line script
      run: |
        echo hello first line
        echo hello second line
